POST http://localhost:8000/api/notes
content-type: application/json

{
    "title": "Note No. 1",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    "author": "John Doe"
}

####
GET http://localhost:8000/api/notes