POST http://localhost:8000/api/notes
content-type: application/json

{
    "title": "A Very Important Note",
    "content": "Alpah asjbjknagh asbfjnag ajhgjkadg adjgklajdg adnkgdalg",
    "author": "Dames Doe"
}

####
GET http://localhost:8000/api/notes