POST http://localhost:8000/api/notebooks
content-type: application/json

{
    "title": "2nd Notebook"
}

####
GET http://localhost:8000/api/notebooks

####
DELETE http://localhost:8000/api/notebooks/63ebba1931195ae67bb0e845