POST http://localhost:8000/api/notebooks
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpEb2UiLCJpZCI6IjY0MjcyMmMzNzJlZTg5YzVhM2RlYTNiMSIsImlhdCI6MTY4MDM1MjE3MH0.dMF4cVs8Rt8Ckb4oXGlY4ZOZX30FxJraHw7JKO_ulkw

{
    "title": "Fifth Notebook"
}

####
PUT http://localhost:8000/api/notebooks/6426c4ec23998dbed4521a44
content-type: application/json

{
    "title": "Testing Notebook"
}

####
GET http://localhost:8000/api/notebooks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpEb2UiLCJpZCI6IjY0MjcyMmMzNzJlZTg5YzVhM2RlYTNiMSIsImlhdCI6MTY4MDM1MjE3MH0.dMF4cVs8Rt8Ckb4oXGlY4ZOZX30FxJraHw7JKO_ulkw

#####
GET http://localhost:8000/api/notebooks/64282443419538d5cc7cf117
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpEb2UiLCJpZCI6IjY0MjcyMmMzNzJlZTg5YzVhM2RlYTNiMSIsImlhdCI6MTY4MDM1MjE3MH0.dMF4cVs8Rt8Ckb4oXGlY4ZOZX30FxJraHw7JKO_ulkw


####
GET http://localhost:8000/api/notebooks/64282443419538d5cc7cf117
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFub24iLCJpZCI6IjY0MjgzODNlOGUxN2Y1OWQxNDgyY2NjYiIsImlhdCI6MTY4MDM1NzQ3Nn0.H_Cgq_4pe7EnOtt4UuEp_cg-H8i1hGXJ6SmCweLvBoE

####
DELETE http://localhost:8000/api/notebooks/63f86b23809c60418c453602