POST http://localhost:8000/api/notes
content-type: application/json

{
    "title": "A Very Important Note",
    "content": "Alpah asjbjknagh asbfjnag ajhgjkadg adjgklajdg adnkgdalg",
    "author": "Dames Doe",
    "notebookID": "63e609c5233ef431c7c88c99"
}

####
GET http://localhost:8000/api/notes