POST http://localhost:8000/api/notebooks
content-type: application/json

{
    "title": "Third Notebook"
}

####
PUT http://localhost:8000/api/notebooks/6426c4ec23998dbed4521a44
content-type: application/json

{
    "title": "Testing Notebook"
}

####
GET http://localhost:8000/api/notebooks

####
DELETE http://localhost:8000/api/notebooks/63f86b23809c60418c453602