POST http://localhost:8000/api/notes
content-type: application/json

{
    "title": "Final Check",
    "content": "Checking UpdatedNote return",
    "author": "John Doe",
    "notebookID": "64253d115c6663c1adda83d7"
}

####
GET http://localhost:8000/api/notes

####
GET http://localhost:8000/api/notes/64253d155c6663c1adda83e1

####
DELETE http://localhost:8000/api/notes/64253d155c6663c1adda83e1
######
PUT http://localhost:8000/api/notes/6425dc2a1736900b00628fae
content-type: application/json

{
    "title": "Seventh Check"
}