POST http://localhost:8000/api/users
content-type: application/json

{
    "username": "anon",
    "name": "Anonymous",
    "password": "qwerty"
}

####
GET http://localhost:8000/api/users

####
GET http://localhost:8000/api/users/641b465133f999c895309327

####
PUT http://localhost:8000/api/users/641b465133f999c895309327
content-type: application/json

{
    "name": "geo"
}